### ISSUE TITLE
failure with some sets of limitation (vel, accc, jrk) 

### ISSUE THREAD

**Issue by mahmoud-a-ali** [nameofuser1/py-scurve#1]
### Description
A failure to generate s-curve trajectories for some sets of parameters:
First case: for some parameters, acceleration profile has a square wave profile and velocity takes trapezoidal or linear shape (velocity is not taking the S-shape any more).
Second case: give weird trajectories. 
Third case: it could not find the correct a_max for some sets.

### Environment
OS Version: Ubuntu 16.04
source: @11da2fddc

### Steps to reproduce
**For the first case:** use these parameters:
`   q0 = [-2., 0., 10.]
    q1 = [20., 15., -10.]
    v0 = [0., 5., 0.]
    v1 = [2, 0.4, 0.2]
    v_max = 05.
    a_max = 30.
    j_max = 100.
    T = None`

**For the second case:** use these parameters:
` q0 = [-.2, 0., 0.]
    q1 = [.2, 1, -.30]
    v0 = [0., 1., 0.]
    v1 = [.1, 0.0, 0.2]
    v_max = 20.
    a_max = 30.
    j_max = 100.
    T = None`

![issue_1](https://user-images.githubusercontent.com/46086657/58077070-10535980-7bac-11e9-8038-2ac70d650958.png)

**Comment by mahmoud-a-ali** [comment]
add photo

**Comment by nameofuser1** [comment]
Thank you for feedback! Found a bug. Now it should work!
