### ISSUE TITLE
wrong profile when max velocity can not be reached

### ISSUE THREAD

**Issue by stefanbesler** [nameofuser1/py-scurve#3]
Hi @nameofuser1, first of all, thanks for this package, I am using it to validate my own TwinCAT library for coupled movement of multiple axes in a robotic solution. I think I found a bug in the package that occurs when a the velocity of a movement is so high, that it can not be actually reached.
```
from pyscurve import ScurvePlanner, plot_trajectory
p = ScurvePlanner()
v_max = 771 # mm/s
v_max = 772 # mm/s
tr = p.plan_trajectory([48.], [18.], [0.], [0.], v_max, 25000., 25000./0.008)
plot_trajectory(tr, 0.0001)
print(tr.time)
```

* when max velocity can be reached (v_max = 771 mm/s) the total time of the movement is 0.078s
![image](https://user-images.githubusercontent.com/11271989/76213443-fbaf8300-620a-11ea-9b72-cc16bdf6ae87.png)

* when max velocity can be reached (v_max = 772 mm/s) the total time of the movement is 0.204s
![image](https://user-images.githubusercontent.com/11271989/76213401-e4709580-620a-11ea-8f39-f36d237b42da.png)

However, there should be a smooth transition between these cases, and the total time for the movement should be something like. I noticed that the max acceleration used in case 2 is merely 0.1 * a_max

`2 * sqrt( (q1 - q0) / a_max ) + a_max / j_max`

**Comment by nameofuser1** [comment]
Hi! 

Thank you for your interest. I'll investigate it.

**Comment by nameofuser1** [comment]
Check it please. Should be fixed.
