### ISSUE TITLE
v_max and a_max sometimes appear to be switched

### ISSUE THREAD

**Issue by idoria75** [nameofuser1/py-scurve#7]
First of all, thanks for the library, it is really useful.

Based on the examples given on the README, I changed the values of the script to make sense to my application:

```python
from pyscurve import ScurvePlanner, plot_trajectory
import numpy as np

if __name__ == "__main__":
    q0 = [-2., 0.]
    q1 = [2., 5.]
    v0 = [0., 0.]
    v1 = [0., 0.]
    v_max = 0.5
    a_max = 2
    j_max = 10.

    p = ScurvePlanner()

    tr = p.plan_trajectory(q0, q1, v0, v1, v_max, a_max, j_max)
    plot_trajectory(tr, dt=0.01)
```

However, that is the result of plot_trajectory:
![result](https://user-images.githubusercontent.com/19222198/105213563-c4a63f80-5b46-11eb-9880-59d310e0c49e.png)

Note how my velocity limit is 0.5 and the speed profile on the left reaches values higher than 1. Also, the acceleration on the left saturates at 0.5, which is my velocity limit.

Do you have any clue on what could be causing this behavior?

**Comment by idoria75** [comment]
I renamed the title because the use-case I had before had shown this issue on the 2nd trajectory. But on this case it happens on the 2nd trajectory:

```python
from pyscurve import ScurvePlanner, plot_trajectory
import numpy as np

if __name__ == "__main__":
    q0 = [10., 0.]
    q1 = [4., 5.]
    v0 = [0., 0.]
    v1 = [0., 0.]
    v_max = 0.5
    a_max = 1
    j_max = 10.

    p = ScurvePlanner()

    tr = p.plan_trajectory(q0, q1, v0, v1, v_max, a_max, j_max)
    plot_trajectory(tr, dt=0.01)
```

![scurve2](https://user-images.githubusercontent.com/19222198/105214546-0daac380-5b48-11eb-8049-701cb1814c93.png)

**Comment by nameofuser1** [comment]
Fix merged
